### PR TITLE
Axes v0.4

### PR DESCRIPTION
**Pull request by will-moore**
Starting to implement Axes and Transformations (see https://github.com/ome/ngff/pull/57).
cc @constantinpape 

This requires  https://pypi.org/project/ome-zarr/0.3a1/ for mask writing and new HCS metadata (row/column Indexes).

To test:
```
$ omero zarr export Image:6001240     # /6001240.zarr/.zattrs  should have new axes (see below)
$ omero zarr masks Image:6001240      # /6001240.zarr/labels/0/.zattrs should also have new axes

$ omero zarr export Plate:1234           # 1234.zarr/.zattrs each 'well' should have rowIndex and columnIndex

```

Some data exported with this PR can be viewed with vizarr:
https://deploy-preview-139--vizarr.netlify.app/?source=https://minio-dev.openmicroscopy.org/idr/v0.4/2022-01-05/idr0062/6001240.zarr (with PR at https://github.com/hms-dbmi/vizarr/pull/139)

Plate data: https://minio-dev.openmicroscopy.org/idr/v0.4/2022-01-24/plates/idr0004/1752.zarr

Exported NGFF includes:
 - axes - eg. at https://minio-dev.openmicroscopy.org/idr/v0.4/2022-01-05/idr0062/6001240.zarr/.zattrs :
```
    "axes": [
                {
                    "name": "c",
                    "type": "channel"
                },
                {
                    "name": "z",
                    "type": "space",
                    "units": "micrometer"
                },
                {
                    "name": "y",
                    "type": "space",
                    "units": "micrometer"
                },
                {
                    "name": "x",
                    "type": "space",
                    "units": "micrometer"
                }
            ]
```
and each `dataset` has transformations. E.g. czyx image is scaled along axis `z, y, x` or `[1, 2, 3]`:
NB: this format is still being discussed at https://github.com/ome/ngff/pull/57#pullrequestreview-836379663
```
                  "transformations": [
                        {
                            "axisIndices": [
                                1,
                                2,
                                3
                            ],
                            "scale": [
                                0.5002025531914894,
                                0.3603981534640209,
                                0.3603981534640209
                            ],
                            "type": "scale"
                        }
                    ]
```

### CODE REVIEW

**Comment by constantinpape** [comment]
For me installation of `cfunits` via `conda install -c conda-forge cfunits` went smooth and without any issues. What system did you try this on? Maybe we can raise this issue with the conda-forge maintainers of cfunits / uduints2.

**Comment by will-moore** [comment]
Hah! OK, it worked this time (on an aging Mac 10.14).
But I still don't know if I want to make this a dependency. I might try to validate all the units that we get from OMERO for length (and if not valid then map to a valid unit).

It seems that a lot of things are valid (see below), so if the spec allows all of these, then it becomes very hard to read OME-NGFF data without having `cfunits` installed. If the spec were more restrictive, then we might not have to make `cfunits` a dependency of `napari-ome-zarr`, which would be nice. I'll add a comment to the spec PR... 

```>>> from cfunits import Units
>>> Units("micrometer").isvalid
True
>>> Units("micrometre").isvalid
True
>>> Units("micrometres").isvalid
True
>>> Units("micrometress").isvalid
False
>>> Units("micrometres")
<Units: micrometres>
>>> Units("micrometre")
<Units: micrometre>
>>> Units("nm")
<Units: nm>
>>> Units("nm").isvalid
True
>>> Units("nanom").isvalid
True
>>> Units("nanome").isvalid
True
>>> Units("nanomet").isvalid
False
>>> Units("nanometer").isvalid
True
>>> Units("nanometre").isvalid
True
>>> Units("nanometre").formatted()
'1e-09 m'
>>> Units("nanome").formatted()
'1.602176487e-31 C'
>>> Units("nanome").units
'nanome'
>>> Units("nanom").units
'nanom'
>>> Units("nano").units
'nano'
>>> Units("nano").formatted()
>>> Units("nanom").formatted()
'1e-09 m'
>>> Units("nanometer").formatted()
'1e-09 m'
>>> Units("nanometre").formatted()
'1e-09 m'
>>> Units("nanom").formatted()
'1e-09 m'
```

File: src/omero_zarr/raw_pixels.py [hunk 1]
```diff
@@ -275,14 +328,20 @@ def plate_to_zarr(plate: omero.gateway._PlateWrapper, args: argparse.Namespace)
 
 def add_multiscales_metadata(
```
Comment (sbesson) [inline src/omero_zarr/raw_pixels.py:329]: Suggested in https://github.com/ome/ome-zarr-py/pull/124#discussion_r783818649, I would propose we use the opportunity of the upcoming API changes associated with the 0.4 support to remove the duplication in our code base. In this case, I expect we should be able to start consuming `ome_zarr.writer.write_multiscales_metada` directly.

Comment (will-moore) [reply src/omero_zarr/raw_pixels.py]: Done in 70975a4

**Comment by will-moore** [comment]
Plate data exported today with current state of this branch and https://pypi.org/project/ome-zarr/0.3a1/
https://minio-dev.openmicroscopy.org/idr/v0.4/2022-01-24/plates/idr0004/1752.zarr 
Screenshot 2022-01-24 at 11 49 10

File: src/omero_zarr/__init__.py [hunk 2]
```diff
@@ -1,6 +1,6 @@
 from ._version import version as __version__
 
-ngff_version = "0.3"
+ngff_version = "0.4"
```
Comment (sbesson) [inline src/omero_zarr/__init__.py:3]: Since you are using the low-level `ome_zarr` writer APIs, there is a possibility of creating a mix of spec versions. I wonder whether this should not become `CurrentFormat().version` to unify?

File: src/omero_zarr/masks.py [hunk 3]
```diff
@@ -303,30 +304,30 @@ def save(self, masks: List[omero.model.Shape], name: str) -> None:
...
-            label_pyramid, pyramid_grp, axes=axes
+            label_pyramid, pyramid_grp, **metadata
         )  # TODO: dtype, chunks, overwite
 
         # Specify and store metadata
         image_label_colors: List[JSONDict] = []
         label_properties: List[JSONDict] = []
         image_label = {
-            "version": "0.3",
+            "version": "0.4",
```
Comment (sbesson) [inline src/omero_zarr/masks.py:330]: Use `VERSION` (or `CurrentFOrmat().version`)?

File: src/omero_zarr/raw_pixels.py [hunk 4]
```diff
@@ -256,39 +253,28 @@ def plate_to_zarr(plate: omero.gateway._PlateWrapper, args: argparse.Namespace)
                 row_group = root.require_group(row)
                 col_group = row_group.require_group(col)
                 field_group = col_group.require_group(field_name)
-                n_levels, axes = add_image(img, field_group, cache_dir=cache_dir)
-                add_multiscales_metadata(field_group, axes, n_levels)
+                add_image(img, field_group, cache_dir=cache_dir)
                 add_omero_metadata(field_group, img)
                 # Update Well metadata after each image
                 col_group.attrs["well"] = {"images": fields, "version": VERSION}
```
Comment (sbesson) [inline src/omero_zarr/raw_pixels.py:259]: Just occurs to me this could also use the underlying `write_plate_metadata` API for additional validation

File: src/omero_zarr/raw_pixels.py [hunk 5]
```diff
@@ -256,39 +253,28 @@ def plate_to_zarr(plate: omero.gateway._PlateWrapper, args: argparse.Namespace)
...
                 max_fields = max(max_fields, field + 1)
             print_status(int(t0), int(time.time()), count, total)
 
         # Update plate_metadata after each Well
-        plate_metadata["wells"] = [{"path": x} for x in well_paths]
-        plate_metadata["field_count"] = max_fields
-        root.attrs["plate"] = plate_metadata
+        write_plate_metadata(
```
Comment (sbesson) [inline src/omero_zarr/raw_pixels.py:264]: What is the rationale for overwriting the plate metadata on each well?

File: src/omero_zarr/util.py [hunk 6]
```diff
@@ -33,3 +35,69 @@ def open_store(name: str) -> FSStore:
         normalize_keys=False,
         mode="w",
     )
+
+
+def marshal_axes(
+    image: ImageWrapper, levels: int = 1, multiscales_zoom: float = 2.0
+) -> Dict[str, List]:
```
Comment (sbesson) [inline src/omero_zarr/util.py:42]: :+1: but this is doing more than just marshalling the axes no?

File: src/omero_zarr/raw_pixels.py [hunk 7]
```diff
@@ -91,6 +91,12 @@ def planeGen() -> np.ndarray:
         cache_file_name_func=get_cache_filename,
     )
 
+    metadata = marshal_axes(image, len(paths))
+
+    write_multiscales_metadata(parent, paths, **metadata)
```
Comment (sbesson) [inline src/omero_zarr/raw_pixels.py:96]: Now that I see this API (introduced in https://github.com/ome/ome-zarr-py/pull/124) in action, I am slightly confused. I think this is primarily because `transformations` is generated from the knowledge of `paths` above and then later re-zipped with `paths` when writing the metadata.

An alternative workflow would be to support `datasets` either as lists of string or dictionaries in  `write_multiscales_metadata`.

**Review by sbesson — COMMENTED** [review]
A few API comments. I have not carried out any functional testing yet

File: src/omero_zarr/raw_pixels.py (hunk 7 above)
Comment (joshmoore) [reply src/omero_zarr/raw_pixels.py:96]: Perhaps slightly related to my thoughts in https://github.com/ome/ome-zarr-py/pull/161#pullrequestreview-862102250

**Comment by sbesson** [comment]
In addition to the various comments above, following this morning's discussion, I have been thinking of ways to exercise the `translation` transformation that is being introduced in https://github.com/ome/ngff/pull/57.

In the OMERO -> OME-NGFF workflow, a potential candidate might be the `WellSample.PositionX` and `WellSample.PositionY` i.e. within the context of a `well` specification have the individual multiscales images registering the X/Y position relative to some well origin so that a client would be able to display a well grid using the absolute positions.

Unless this is something straightforward to implement, I would definitely consider this outside the scope of this PR and limit the `transformations` support to `scale` for now which is the primary use case. The primary reason for mentioning it is that it might something to keep in mind alongside the questions raised in https://github.com/ome/omero-cli-zarr/pull/93#discussion_r790864982 as this translation metadata would be not be available from the `ImageWrapper` itself and would either need to be passed to `add_image` or be added via a follow-up call which would update the metadata.

File: src/omero_zarr/raw_pixels.py (hunk 5 above)
Comment (will-moore) [reply src/omero_zarr/raw_pixels.py:264]: When exporting a large plate, I have found it useful to be able to view it in vizarr before it's complete.
Or if you cancel the export, or it fails at any point, you still have something you can view.

File: src/omero_zarr/util.py (hunk 6 above)
Comment (will-moore) [reply src/omero_zarr/util.py:42]: Yes, but naming things is hard. I didn't think `marshal_axes_and_transformations()` was so neat.
Any suggestions?

File: src/omero_zarr/raw_pixels.py (hunk 7 above)
Comment (will-moore) [reply src/omero_zarr/raw_pixels.py:96]: since `datasets` would include `paths`, we would just have `write_multiscales_metadata(group, datasets)` and remove support for paths? Or if `datasets` is a list of strings, treat it as `paths` (wouldn't break the API, but could be more confusing).

Comment (sbesson) [reply src/omero_zarr/raw_pixels.py:96]: Similar questions and concerns around the usability came up in https://github.com/ome/ome-zarr-py/pull/157 when adding support for `plate.wells` as list of dictionaries alongside list of strings (also corresponding to individual well paths).

At least, I find `List[Union[str, dict]]` to be a fairly good compromise that allows to handle both the simple use case where a minimal valid spec is generated from a list of paths and the extensible scenario where the caller wants to store additional  metadata (and not necessarily specified by the OME-NGFF spec) to the `datasets` element.

File: src/omero_zarr/util.py (hunk 6 above)
Comment (sbesson) [reply src/omero_zarr/util.py:42]: Since `levels` and `multiscales_zoom` are irrelevant for the transformations marshalling, a potential option would be to splitting this into 2 separate calls?

File: src/omero_zarr/raw_pixels.py (hunk 4 above)
Comment (will-moore) [reply src/omero_zarr/raw_pixels.py]: Done in 27df32b

File: src/omero_zarr/masks.py (hunk 3 above)
Comment (will-moore) [reply src/omero_zarr/masks.py:330]: Done in 9194fdd

**Comment by sbesson** [comment]
Trying to use the latest version of this PR, I get

```
(zarr) [sbesson@pilot-zarr1-dev ~]$ omero zarr export Plate:9512 --help

Error loading: /home/sbesson/miniconda3/envs/zarr/lib/python3.9/site-packages/omero/plugins/zarr.py
Traceback (most recent call last):
  File "/home/sbesson/miniconda3/envs/zarr/lib/python3.9/site-packages/omero/cli.py", line 1690, in loadpath
    execfile(str(pathobj), loc)
  File "/home/sbesson/miniconda3/envs/zarr/lib/python3.9/site-packages/past/builtins/misc.py", line 87, in execfile
    exec_(code, myglobals, mylocals)
  File "/home/sbesson/miniconda3/envs/zarr/lib/python3.9/site-packages/omero/plugins/zarr.py", line 1, in <module>
    from omero_zarr.cli import HELP, ZarrControl
  File "/home/sbesson/miniconda3/envs/zarr/lib/python3.9/site-packages/omero_zarr/cli.py", line 15, in <module>
    from .raw_pixels import (
  File "/home/sbesson/miniconda3/envs/zarr/lib/python3.9/site-packages/omero_zarr/raw_pixels.py", line 10, in <module>
    from ome_zarr.writer import (
ImportError: cannot import name 'write_multiscales_metadata' from 'ome_zarr.writer' (/home/sbesson/miniconda3/envs/zarr/lib/python3.9/site-packages/ome_zarr/writer.py)
```

Should the `ome-zarr-py` dependency be upgraded similarly to https://github.com/ome/napari-ome-zarr/pull/31/commits/dc4f0bd83d03df870b568977589883037fa95cb1?

**Comment by will-moore** [comment]
@sbesson Fixed ome-zarr requirement.

File: src/omero_zarr/raw_pixels.py (hunk 7 above)
Comment (will-moore) [reply src/omero_zarr/raw_pixels.py]: See https://github.com/ome/ome-zarr-py/pull/162

**Comment by will-moore** [comment]
That last commit uses PR: https://github.com/ome/ome-zarr-py/pull/162

**Comment by will-moore** [comment]
@joshmoore @sbesson I guess we probably don't want that last commit if this PR goes into a pre-release of omero-cli-zarr that works with `ome-zarr>=0.3a1`?
So, I can revert that and then we can make those changes in a follow-up PR?
I also have a commit locally that uses `"scale": {"x": 0.5, "y":0.5: "z": 0.3}` format and I guess that should go into a later PR too (so that the pre-releases are all aligned on the `axisIndices` format?

**Comment by sbesson** [comment]
Yes :+1: for getting a pre-release of omero-cli-zarr with `ome-zarr-py 0.3.0a` and focus on the new writing API and updated `scale` form as a follow-up set of pre-releases.

**Comment by will-moore** [comment]
Reverted de7703a

**Review by sbesson — APPROVED** [review]
The most important concerns above have been addressed and new PRs have been opened upstream to introduce new metadata writing API. No objection from my side to getting this merged and releases as `0.3.0a1`. @joshmoore is there anything from your side that should be captured as an issue and addressed in the next development segment?

**Comment by will-moore** [comment]
As discussed today, a screenshot illustrating the use of different names for Z/T axes and how it looks in Vizarr:
cc @joshmoore @sbesson @constantinpape 

Screenshot 2022-01-26 at 22 39 39

**Comment by constantinpape** [comment]
Thanks @will-moore. Is this the dataset from https://minio-dev.openmicroscopy.org/idr/v0.4/2022-01-05/idr0062/6001240.zarr?
I can open that one with Fiji/MoBIE now, but I am not sure if it's quite correct yet:
image

**Comment by will-moore** [comment]
Looking at https://deploy-preview-139--vizarr.netlify.app/?source=https://minio-dev.openmicroscopy.org/idr/v0.4/2022-01-05/idr0062/6001240.zarr (use Firefox - bugs on Chrome just now).
The `.zattrs` has:
```
"datasets": [
                {
                    "path": "0",
                    "transformations": [
                        {
                            "axisIndices": [
                                1,
                                2,
                                3
                            ],
                            "scale": [
                                0.5002025531914894,
                                0.3603981534640209,
                                0.3603981534640209
                            ],
                            "type": "scale"
                        }
                    ]
                },
```
which should mean it applies to both channels? It looks like your example has different transforms applied to the 2 channels?

**Comment by sbesson** [comment]
As discussed this morning, merging and tagging this as `0.3.0a1` alongside all the other Python libraries pre-releases created ahead of the NGFF community call. 
Ongoing work is happening in #103 to support the latest proposed changes to the 0.4 specification and the conversation on how to validate transformations started above can happen there.
